### ISSUE TITLE
function in .bashrc breaks ability to directlz jump into the user's home with cd

### ISSUE THREAD

**Issue by dulhaver** [victoriadrake/dotfiles#1]
this function in your [`.bashrc`](https://github.com/victoriadrake/dotfiles/blob/ubuntu-19.10/.bashrc) breaks the ability to jump to the users home with a simple `cd`

```
# Show contents of dir after action
function cd () {
    builtin cd "$1"
    ls -ACF
}
```
I lack knowledge to eliminate the error, so there is no PR coming with this

**Comment by victoriadrake** [comment]
Fixed. Thank you for opening the issue!
